# fly.toml file generated for rnorth-gts on 2022-11-18T17:02:03Z

app = "rnorth-gts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  GTS_HOST = "fedi.rnorth.org"
  GTS_ACCOUNT_DOMAIN = "rnorth.org"
  GTS_DB_TYPE = "sqlite"
  GTS_DB_ADDRESS = "/data/sqlite.db"
  GTS_STORAGE_LOCAL_BASE_PATH = "/data/storage"
  GTS_ACCOUNTS_REGISTRATION_OPEN = "false"
# Note that OIDC does not support admin groups when using Google (free, non-workspace) as the IDP.
# So the current configuration is a little bit useless.
  GTS_OIDC_ENABLED = "true"
  GTS_OIDC_IDP_NAME = "Google"
  GTS_OIDC_ISSUER = "https://accounts.google.com"
  GTS_OIDC_SCOPES= "openid email profile"

[mounts]
  source="gts_data"
  destination="/data"

# [experimental]
#   allowed_public_ports = []
#   auto_rollback = true

[[services]]
  # http_checks = []
  internal_port = 8080
  # processes = ["app"]
  protocol = "tcp"
  # script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    # force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
